version: '2'
services:
  mongo:
    image: mongo:2
    ports:
      - "27017:27017"
  elasticsearch:
    image: elasticsearch:2
    ports:
      - "9200:9200"
      - "9300:9300"
  server:
    build: ./
    ports:
     - "9000:9000"
    depends_on:
      - elasticsearch
      - mongo
    environment:
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: elasticsearch
  slave:
    build: ./
    depends_on:
      - elasticsearch
      - mongo
    environment:
      GRAYLOG_IS_MASTER: "false"
      GRAYLOG_WEB_ENABLE: "false"
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: elasticsearch
